random_seed:
  numpy: 12345
  networkx: 896803

# specify default configurations for each of the subfolders
defaults:
  - dataset: default
  - gaussians: low_frequency
  - plotting: default
  - topology: geometric_graph
  - _self_ # https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order/
